---
title: "UpdatedKuwaitPlots"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
##All the packages essential to running my code, there might even be some that I never use, but most of them are needed and they are here:
library(plyr)
library(tidyverse)
library(forcats)
library(lubridate)
library(openair)
library(ggplot2)
library(zoo)
library(readr)
library(scales)
library(ggthemes)
library(gridExtra)
```



```{r datasets}
##May not use all these datasets, but lets import them either way. 
setwd("~/Desktop/4Years@Reed_2/Summer Research/Kuwait202")
KuwaitFullJoin <- read_csv("Rcode/KuwaitFullJoin.csv")
KuwaitWeather <- read_csv("Rcode/KuwaitWeather.csv")
KuwaitPMFull <- read_csv("Rcode/KuwaitPMFull.csv")
```



```{r sample plots}
OAFullJoin <- KuwaitFullJoin  %>%
select(date, ws, wd, RawConc, tempc, relh, visibility, AQI) 

###Lets mutate it becaseu i dont know how else to make a nice looking faceted plot.
KuwaitFullJoinFacet<- KuwaitFullJoin%>%
mutate(dayhour = make_datetime(2020,1,Day, Hour))


##Here is our first plot
#now lets make the plot

ggplot(data = KuwaitFullJoinFacet, 
       mapping = aes(x = dayhour,
                     y = RawConc,
                     fill = Year)) +  geom_line() + facet_wrap(~Month_Name)+
  labs(title = "Raw Concentration and Time", x = "Months", y = "Raw Concentration (UG/M3)" ) +
  theme_bw()
##We cannot tell which year is which so lets try something else
##Changing the fill to month_name, adding color=year
ggplot(data = KuwaitFullJoinFacet, 
       mapping = aes(x = dayhour,
                     y = RawConc,
                     fill = Month_Name, 
                     color=Year)) +  geom_line() + facet_wrap(~Month_Name)+
  labs(title = "Raw Concentration and Time", x = "Months", y = "Raw Concentration (UG/M3)" ) +
  theme_bw()
##This gave us a plot with miltiple years in each mmonth, useful. can we try that with the old dataset?
ggplot(data = KuwaitFullJoin, 
       mapping = aes(x = date,
                     y = RawConc,
                     fill = Month_Name, 
                     color=Year)) +  geom_line() + facet_wrap(~Month_Name)+
  labs(title = "Raw Concentration and Time", x = "Months", y = "Raw Concentration (UG/M3)" ) +
  theme_bw()
##The dates are all messed up, hm lets go back i guess. I am not sure how to fix that.
##i took out fill
ggplot(data = KuwaitFullJoinFacet, 
       mapping = aes(x = dayhour,
                     y = RawConc,
                      
                     color=Year)) +  geom_line() + facet_wrap(~Month_Name)+
  labs(title = "Raw Concentration and Time", x = "Months", y = "Raw Concentration (UG/M3)" ) +
  theme_bw()

##Taking out fill doesnt seem to change anything, lets just add some better colors and make the bottom better. 
ggplot(data = KuwaitFullJoinFacet, 
       mapping = aes(x = dayhour,
                     y = RawConc,
                     color=Year)) +  geom_line() + facet_wrap(~Month_Name)+
  labs(title = "Raw Concentration and Time", x = "Months", y = "Raw Concentration (UG/M3)" )+ theme_bw()
##So I cannot change the colors, but lets just look at 2020

KuwaitFullJoinFacet2020<- KuwaitFullJoin%>%

  filter(Year== 2020)
ggplot(data = KuwaitFullJoinFacet, 
       mapping = aes(x = dayhour,
                     y = RawConc)) +  geom_line() + facet_wrap(~Month_Name)+
  labs(title = "Raw Concentration and Time in 2020", x = "Months", y = "Raw Concentration (UG/M3)" )+ theme_bw()

```



```{r daily means}
###Taking the daily means
KuwaitFullJoin$Year <- as.numeric(KuwaitFullJoin$Year)
AVGKuwaitBaseline <- timeAverage(KuwaitFullJoin, avg.time = "day")

AVGKuwaitBaseline<- AVGKuwaitBaseline%>%
 mutate(
   Month_Name = case_when(
      Month == '1' ~ "Jan",
      Month == '2' ~ "Feb",
      Month == '3' ~ "Mar",
      Month == '4' ~ "Apr",
      Month == '5' ~ "May",
      Month == '6' ~ "Jun",
      Month == '7' ~ "Jul",
      Month == '8' ~ "Aug",
      Month == '9' ~ "Sep",
      Month == '10' ~ "Oct",
      Month == '11' ~ "Nov",
      Month == '12' ~ "Dec" ) )%>%
  mutate(Month_Name = factor(Month_Name))%>%
  
 
    mutate(
    YearName = case_when(
      Year =='2016' ~ "2016",
      Year == '2017'~ "2017",
      Year == '2018'~ "2018",
      Year == '2019'~ "2019",
      Year == '2020'~ "2020"))
AVGKuwaitBaseline$YearName <- as.factor(AVGKuwaitBaseline$YearName)
 AVGKuwaitBaseline$Month_Name <- fct_reorder(AVGKuwaitBaseline$Month_Name, 
                                          AVGKuwaitBaseline$Month, 
                                          min)
##Now comes our boxplot
ggplot(data = AVGKuwaitBaseline, 
       mapping = aes(x = Month_Name,
                     y = RawConc,
                      fill = YearName)) +  geom_boxplot()+
  labs(title = "Raw Concentration and Time", x = "Months", y = "Raw Concentration (UG/M3)", fill = "Year")+ theme_bw()


```


```{r}
##Now lets take avgs from 2017-2019 and then compare it with the 2020 data. 
##here is the chunk for 2020, less needs to be done here.
KuwaitFullJoin2020 <-KuwaitFullJoin%>%
filter (Year == 2020)
KuwaitFullJoin2020$temp <- as.numeric(KuwaitFullJoin2020$temp)
KuwaitFullJoin2020$YearName <- as.factor(KuwaitFullJoin2020$YearName)
##Here is the first chunk
KuwaitFullJoin20172019 <-KuwaitFullJoin%>%
filter (Year != 2020)%>%
  mutate(date = make_datetime(2020,Month,Day, Hour))
KuwaitFullJoin20172019$date <- as.POSIXct(KuwaitFullJoin20172019$date, format = '2019-%m-%d')
KuwaitFullJoin20172019$temp <- as.numeric(KuwaitFullJoin20172019$temp)
KuwaitFullJoin20172019 <- aggregate(cbind(ws,RawConc, visibility, wd, relh,temp, AQI, Month, Day, Hour ) ~ (date), data=KuwaitFullJoin20172019, FUN=mean)

KuwaitFullJoin20172019$Year <- 2019
  
KuwaitFullJoin20172019 <- KuwaitFullJoin20172019 %>%
  filter (date <= as.Date("2020-12-15"))%>% ##change if updated dates
##Lets add Month_Name and YearName back in.
  mutate(
   Month_Name = case_when(
      Month == '1' ~ "January",
      Month == '2' ~ "February",
      Month == '3' ~ "March",
      Month == '4' ~ "April",
      Month == '5' ~ "May",
      Month == '6' ~ "June",
      Month == '7' ~ "July",
      Month == '8' ~ "August",
      Month == '9' ~ "September",
      Month == '10' ~ "October",
      Month == '11' ~ "November",
      Month == '12' ~ "December" ) )%>%
  mutate(Month_Name = factor(Month_Name))%>%
    mutate(
    YearName = case_when(
      Year =='2016' ~ "2016",
      Year == '2017'~ "2017",
      Year == '2018'~ "2018",
      Year == '2019'~ "2019",
      Year == '2020'~ "2020"))
KuwaitFullJoin20172019$YearName <- as.factor(KuwaitFullJoin20172019$YearName)

KuwaitBaseline=full_join(KuwaitFullJoin20172019,KuwaitFullJoin2020,by=c("ws","RawConc", "visibility", "wd", "relh", "temp", "AQI", "Month", "Day", "Hour", "date", "Year", "YearName", "Month_Name"))
  



AVGKuwaitBaseline <- timeAverage(KuwaitBaseline, avg.time = "day")
##We have to add Month_Name and YearName back in again, oy vey
AVGKuwaitBaseline<- AVGKuwaitBaseline%>%
 mutate(
   Month_Name = case_when(
      Month == '1' ~ "January",
      Month == '2' ~ "February",
      Month == '3' ~ "March",
      Month == '4' ~ "April",
      Month == '5' ~ "May",
      Month == '6' ~ "June",
      Month == '7' ~ "July",
      Month == '8' ~ "August",
      Month == '9' ~ "September",
      Month == '10' ~ "October",
      Month == '11' ~ "November",
      Month == '12' ~ "December" ) )%>%
  mutate(Month_Name = factor(Month_Name))%>%
    mutate(
    YearName = case_when(
      Year =='2016' ~ "2016",
      Year == '2017'~ "2017",
      Year == '2018'~ "2018",
      Year == '2019'~ "2019",
      Year == '2020'~ "2020"))
AVGKuwaitBaseline$YearName <- as.factor(AVGKuwaitBaseline$YearName)


AVGKuwaitFullJoin20172019 <- timeAverage(KuwaitFullJoin20172019, avg.time = "day")
KuwaitFullJoin20172019<- KuwaitFullJoin20172019%>%
 mutate(
   Month_Name = case_when(
      Month == '1' ~ "January",
      Month == '2' ~ "February",
      Month == '3' ~ "March",
      Month == '4' ~ "April",
      Month == '5' ~ "May",
      Month == '6' ~ "June",
      Month == '7' ~ "July",
      Month == '8' ~ "August",
      Month == '9' ~ "September",
      Month == '10' ~ "October",
      Month == '11' ~ "November",
      Month == '12' ~ "December" ) )%>%
  mutate(Month_Name = factor(Month_Name))%>%
  
 
    mutate(
    YearName = case_when(
      Year =='2016' ~ "2016",
      Year == '2017'~ "2017",
      Year == '2018'~ "2018",
      Year == '2019'~ "2019",
      Year == '2020'~ "2020"))
KuwaitFullJoin20172019$YearName <- as.factor(KuwaitFullJoin20172019$YearName)
 KuwaitFullJoin20172019$Month_Name <- fct_reorder(KuwaitFullJoin20172019$Month_Name, 
                                          KuwaitFullJoin20172019$Month, 
                                          min)
 AVGKuwaitFullJoin2020 <- timeAverage(KuwaitFullJoin2020, avg.time = "day")
KuwaitFullJoin2020<- KuwaitFullJoin2020%>%
 mutate(
   Month_Name = case_when(
      Month == '1' ~ "January",
      Month == '2' ~ "February",
      Month == '3' ~ "March",
      Month == '4' ~ "April",
      Month == '5' ~ "May",
      Month == '6' ~ "June",
      Month == '7' ~ "July",
      Month == '8' ~ "August",
      Month == '9' ~ "September",
      Month == '10' ~ "October",
      Month == '11' ~ "November",
      Month == '12' ~ "December" ) )%>%
  mutate(Month_Name = factor(Month_Name))%>%
  
 
    mutate(
    YearName = case_when(
      Year =='2016' ~ "2016",
      Year == '2017'~ "2017",
      Year == '2018'~ "2018",
      Year == '2019'~ "2019",
      Year == '2020'~ "2020"))
KuwaitFullJoin2020$YearName <- as.factor(KuwaitFullJoin2020$YearName)
 KuwaitFullJoin2020$Month_Name <- fct_reorder(KuwaitFullJoin2020$Month_Name, 
                                          KuwaitFullJoin2020$Month, 
                                          min)
```



```{r}
##And now for some plots!
ggplot() + 
  geom_line(data = KuwaitFullJoin2020, aes(x = date, y =RawConc), color = "blue") +
  geom_line(data = KuwaitFullJoin20172019, aes(x = date, y = RawConc), color = "red") +
  
   labs(title = "Raw Concentration and Time 2017-2019 vs 2020", x = "Months", y = "Raw Concentration (UG/M3)" ) +
  theme_bw()
##I am not sure how to get rid of the year on the axis, but this should work for now

##Now lets do some avgs
ggplot() + 
  geom_line(data = AVGKuwaitFullJoin2020, aes(x = date, y =RawConc), color = "blue") +
  geom_line(data = AVGKuwaitFullJoin20172019, aes(x = date, y = RawConc), color = "red") +
  
   labs(title = "Avg Raw Concentration and Time", x = "Months", y = "Raw Concentration (UG/M3)" ) +
  theme_bw()
##Still some biig peaks

##Lets do RH and RawConc in 2020
ggplot() + 
  geom_line(data = AVGKuwaitFullJoin2020, aes(x = date, y =RawConc), color = "blue") +
  geom_line(data = AVGKuwaitFullJoin2020, aes(x = date, y = relh), color = "Black") +
  
   labs(title = "Avg Raw Concentration and Relative Humidity for 2020", x = "Months", y = "Value" ) +
  theme_bw()
##lets do visibility
ggplot() + 
  geom_line(data = AVGKuwaitFullJoin2020, aes(x = date, y =RawConc), color = "blue") +
  geom_line(data = AVGKuwaitFullJoin2020, aes(x = date, y = visibility), color = "Black") +
  
   labs(title = "Avg Raw Concentration and Visibility for 2020", x = "Months", y = "Value" ) +
  theme_bw()
##Lets try another plot, can barely see the visibility line
coeff <- 10
ggplot(AVGKuwaitFullJoin2020, aes(x=date)) +  geom_line( aes(y=visibility),  color="black") + 
  geom_line( aes(y=RawConc/ coeff),  color="blue") +
  scale_y_continuous(
     # Features of the first axis
    name = "Visibility",
    # Add a second axis and specify its features
   sec.axis = sec_axis(~.*coeff, name="Raw Concentration (UG/M3)")
  ) + theme_bw()+
labs(title = "Avg Raw Concentration and Visibility for 2020")



```

```{r}
##Now lets look at years past

ggplot() + 
  geom_line(data = AVGKuwaitFullJoin20172019, aes(x = date, y =RawConc), color = "blue") +
  geom_line(data = AVGKuwaitFullJoin20172019, aes(x = date, y = relh), color = "black") +
  
   labs(title = "Avg Raw Concentration and Relative Humidity 2017-2019 avgs", x = "Months", y = "Value" ) +
  theme_bw()

coeff <- 10
ggplot(AVGKuwaitFullJoin20172019, aes(x=date)) +  geom_line( aes(y=visibility),  color="black") + 
  geom_line( aes(y=RawConc/ coeff),  color="blue") +
  scale_y_continuous(
     # Features of the first axis
    name = "Visibility",
    # Add a second axis and specify its features
   sec.axis = sec_axis(~.*coeff, name="Raw Concentration (UG/M3)")
  ) + theme_bw()+
labs(title = "Avg Raw Concentration and Visibility for 2017-2019")

```


```{r ##playing around w openair}
##playing around w openair
timeVariation(KuwaitFullJoin20172019, pollutant = "RawConc", main = " PM (UG/M3)from 2017-2019 ", cols = "jet")
timeVariation(KuwaitFullJoin2020, pollutant = "RawConc", main = "PM Concentrations (UG/M3) in 2020", cols = "jet")

a <- polarPlot(KuwaitFullJoin20172019, pollutant = "RawConc", main = " PM (UG/M3)from 2017-2019 ",  cols = "jet")
b <- polarPlot(KuwaitFullJoin2020,  pollutant = "RawConc", main = "PM Concentrations (UG/M3) in 2020 ",  cols = "jet")
print(a, split = c(1, 1, 2, 1))
print(b, split = c(2, 1, 2, 1), newpage = FALSE)
c <- timeVariation(KuwaitFullJoin2020, pollutant = "RawConc",  cols = "jet")
print(b, split = c(1, 1, 2, 1))
print(c, split = c(2, 1, 2, 1), subset = "month", newpage = FALSE)
```


```{r}
##Now lets remove the dust storms
KuwaitFilter200 <- KuwaitFullJoin%>%
  filter (RawConc <= 200)

##Now lets take the avges of that
AVGKuwaitFilter200 <- timeAverage(KuwaitFilter200, avg.time = "day")
##We have to add Month_Name and YearName back in again, oy vey
AVGKuwaitFilter200<- AVGKuwaitFilter200%>%
 mutate(
   Month_Name = case_when(
      Month == '1' ~ "January",
      Month == '2' ~ "February",
      Month == '3' ~ "March",
      Month == '4' ~ "April",
      Month == '5' ~ "May",
      Month == '6' ~ "June",
      Month == '7' ~ "July",
      Month == '8' ~ "August",
      Month == '9' ~ "September",
      Month == '10' ~ "October",
      Month == '11' ~ "November",
      Month == '12' ~ "December" ) )%>%
  mutate(Month_Name = factor(Month_Name))%>%
    mutate(
    YearName = case_when(
      Year =='2016' ~ "2016",
      Year == '2017'~ "2017",
      Year == '2018'~ "2018",
      Year == '2019'~ "2019",
      Year == '2020'~ "2020"))
AVGKuwaitFilter200$YearName <- as.factor(AVGKuwaitFilter200$YearName)

##Now lets separate the years and and take those avgs to makes some plots

KuwaitFilter2020 <-KuwaitFilter200%>%
filter (Year == 2020)
KuwaitFilter2020$temp <- as.numeric(KuwaitFilter2020$temp)
KuwaitFilter2020$YearName <- as.factor(KuwaitFilter2020$YearName)
##Here is the first chunk
KuwaitFilter2019 <-KuwaitFilter200%>%
filter (Year != 2020)%>%
  mutate(date = make_datetime(2020,Month,Day, Hour))
KuwaitFilter2019$date <- as.POSIXct(KuwaitFilter2019$date, format = '2019-%m-%d')
KuwaitFilter2019$temp <- as.numeric(KuwaitFilter2019$temp)
KuwaitFilter2019 <- aggregate(cbind(ws,RawConc, visibility, wd, relh,temp, AQI, Month, Day, Hour ) ~ (date), data=KuwaitFilter2019, FUN=mean)

KuwaitFilter2019$Year <- 2019
  
KuwaitFilter2019 <- KuwaitFilter2019 %>%
  filter (date <= as.Date("2020-12-15"))%>% ##change if updated dates
##Lets add Month_Name and YearName back in.
  mutate(
   Month_Name = case_when(
      Month == '1' ~ "January",
      Month == '2' ~ "February",
      Month == '3' ~ "March",
      Month == '4' ~ "April",
      Month == '5' ~ "May",
      Month == '6' ~ "June",
      Month == '7' ~ "July",
      Month == '8' ~ "August",
      Month == '9' ~ "September",
      Month == '10' ~ "October",
      Month == '11' ~ "November",
      Month == '12' ~ "December" ) )%>%
  mutate(Month_Name = factor(Month_Name))%>%
    mutate(
    YearName = case_when(
      Year =='2016' ~ "2016",
      Year == '2017'~ "2017",
      Year == '2018'~ "2018",
      Year == '2019'~ "2019",
      Year == '2020'~ "2020"))
KuwaitFilter2019$YearName <- as.factor(KuwaitFilter2019$YearName)

KuwaitBaseline=full_join(KuwaitFilter2019,KuwaitFilter2020,by=c("ws","RawConc", "visibility", "wd", "relh", "temp", "AQI", "Month", "Day", "Hour", "date", "Year", "YearName", "Month_Name"))
  

AVGKuwaitFilter20172019 <- timeAverage(KuwaitFilter2019, avg.time = "day")
AVGKuwaitFilter20172019<- AVGKuwaitFilter20172019%>%
 mutate(
   Month_Name = case_when(
      Month == '1' ~ "January",
      Month == '2' ~ "February",
      Month == '3' ~ "March",
      Month == '4' ~ "April",
      Month == '5' ~ "May",
      Month == '6' ~ "June",
      Month == '7' ~ "July",
      Month == '8' ~ "August",
      Month == '9' ~ "September",
      Month == '10' ~ "October",
      Month == '11' ~ "November",
      Month == '12' ~ "December" ) )%>%
  mutate(Month_Name = factor(Month_Name))%>%
  
 
    mutate(
    YearName = case_when(
      Year =='2016' ~ "2016",
      Year == '2017'~ "2017",
      Year == '2018'~ "2018",
      Year == '2019'~ "2019",
      Year == '2020'~ "2020"))
AVGKuwaitFilter20172019$YearName <- as.factor(AVGKuwaitFilter20172019$YearName)
 AVGKuwaitFilter20172019$Month_Name <- fct_reorder(AVGKuwaitFilter20172019$Month_Name, 
                                          AVGKuwaitFilter20172019$Month, 
                                          min)
 AVGKuwaitFilter2020 <- timeAverage(KuwaitFilter2020, avg.time = "day")
AVGKuwaitFilter2020<- AVGKuwaitFilter2020%>%
 mutate(
   Month_Name = case_when(
      Month == '1' ~ "January",
      Month == '2' ~ "February",
      Month == '3' ~ "March",
      Month == '4' ~ "April",
      Month == '5' ~ "May",
      Month == '6' ~ "June",
      Month == '7' ~ "July",
      Month == '8' ~ "August",
      Month == '9' ~ "September",
      Month == '10' ~ "October",
      Month == '11' ~ "November",
      Month == '12' ~ "December" ) )%>%
  mutate(Month_Name = factor(Month_Name))%>%
  
 
    mutate(
    YearName = case_when(
      Year =='2016' ~ "2016",
      Year == '2017'~ "2017",
      Year == '2018'~ "2018",
      Year == '2019'~ "2019",
      Year == '2020'~ "2020"))
AVGKuwaitFilter2020$YearName <- as.factor(AVGKuwaitFilter2020$YearName)
 AVGKuwaitFilter2020$Month_Name <- fct_reorder(AVGKuwaitFilter2020$Month_Name, 
                                          AVGKuwaitFilter2020$Month, 
                                          min)



```


```{r}
##Some Plots with filters

ggplot(data = AVGKuwaitFilter200, 
       mapping = aes(x = Month_Name,
                     y = RawConc,
                      fill = YearName)) +  geom_boxplot()+
  labs(title = "Raw Concentration and Time with PM filter @ 200 UG/M3", x = "Months", y = "Raw Concentration (UG/M3)", fill = "Year" )+ theme_bw()

##Now lets try some line plots

ggplot() + 
  geom_line(data = KuwaitFilter2020, aes(x = date, y =RawConc), color = "blue") +
  geom_line(data = KuwaitFilter2019, aes(x = date, y = RawConc), color = "red") +
  
   labs(title = "Raw Concentration and Time 2017-2019 vs 2020 filter @ 200 UG/M3", x = "Months", y = "Raw Concentration (UG/M3)" ) +
  theme_bw()
##now lets try w some avgs
ggplot() + 
  geom_line(data = AVGKuwaitFilter2020, aes(x = date, y =RawConc), color = "blue") +
  geom_line(data = AVGKuwaitFilter20172019, aes(x = date, y = RawConc), color = "red") +
  
   labs(title = "AVG Raw Concentration and Time 2017-2019 vs 2020 filter @ 200 UG/M3", x = "Months", y = "Raw Concentration (UG/M3)" ) +
  theme_bw()


ggplot() + 
  geom_line(data = AVGKuwaitFilter2020, aes(x = date, y =RawConc), color = "blue") +
  geom_line(data = AVGKuwaitFilter2020, aes(x = date, y = relh), color = "black") +
  
   labs(title = "Avg Raw Concentration and Relative Humidity 2020 with filter @ 200 ug/m3", x = "Months", y = "Raw Concentration (UG/M3)" ) +
  theme_bw()

ggplot() + 
  geom_line(data = AVGKuwaitFilter20172019, aes(x = date, y =RawConc), color = "blue") +
  geom_line(data = AVGKuwaitFilter20172019, aes(x = date, y = relh), color = "black") +
  
   labs(title = "Avg Raw Concentration and Relative Humidity 2017-2019 with filter @ 200 ug/m3", x = "Months", y = "Value" ) +
  theme_bw()

coeff <- 10
ggplot(AVGKuwaitFilter2020, aes(x=date)) +  geom_line( aes(y=visibility),  color="black") + 
  geom_line( aes(y=RawConc/ coeff),  color="blue") +
  scale_y_continuous(
     # Features of the first axis
    name = "Visibility",
    # Add a second axis and specify its features
   sec.axis = sec_axis(~.*coeff, name="Raw Concentration (UG/M3)")
  ) + theme_bw()+
labs(title = "Avg Raw Concentration and Visibility for 2020 with filter @ 200 ug/m3 ")

coeff <- 10
ggplot(KuwaitFilter2020, aes(x=date)) +  geom_line( aes(y=visibility),  color="black") + 
  geom_line( aes(y=RawConc/ coeff),  color="blue") +
  scale_y_continuous(
     # Features of the first axis
    name = "Visibility",
    # Add a second axis and specify its features
   sec.axis = sec_axis(~.*coeff, name="Raw Concentration (UG/M3)")
  ) + theme_bw()+
labs(title = "Raw Concentration and Visibility for 2020 with filter @ 200 ug/m3 ")


coeff <- 10
ggplot(AVGKuwaitFilter20172019, aes(x=date)) +  geom_line( aes(y=visibility),  color="black") + 
  geom_line( aes(y=RawConc/ coeff),  color="blue") +
  scale_y_continuous(
     # Features of the first axis
    name = "Visibility",
    # Add a second axis and specify its features
   sec.axis = sec_axis(~.*coeff, name="Raw Concentration (UG/M3)")
  ) + theme_bw()+
labs(title = "Avg Raw Concentration and Visibility for 2017-2019 with filter @ 200 ug/m3 ")

```


```{r ##openair with filters}

KuwaitFilter2020<- KuwaitFilter2020%>%
filter(ws<= 80)

tm1<-timeVariation(KuwaitFilter2019, pollutant = "ws", main = "PM (UG/M3)from 2017-2019 with filter @200 pm ", cols = "jet")
tm2<-timeVariation(KuwaitFilter2020, pollutant = "ws", main = "PM Concentrations (UG/M3) in 2020 with filter @200 pm", cols = "jet")

print(tm1, split = c(1, 1, 2, 1))
print(tm2, split = c(2, 1, 2, 1), newpage = FALSE)

h <- polarPlot(KuwaitFilter2019, pollutant = "RawConc", main = "PM (UG/M3)from 2017-2019 with filter @200 pm",  cols = "jet")
g <- polarPlot(KuwaitFilter2020,  pollutant = "RawConc", main = "PM Concentrations (UG/M3) in 2020 with filter @200 pm",  cols = "jet")

avg1<-polarPlot(AVGKuwaitFilter20172019, pollutant = "RawConc", main = "AVG PM (UG/M3)from 2017-2019 with filter @200 pm ",  cols = "jet")
avg2<-  polarPlot(AVGKuwaitFilter2020,  pollutant = "RawConc", main = " AVG PM Concentrations (UG/M3) in 2020 with filter @200 pm ",  cols = "jet")
print(h, split = c(1, 1, 2, 1))
print(g, split = c(2, 1, 2, 1), newpage = FALSE)

print(avg1, split = c(1, 1, 2, 1))
print(avg2, split = c(2, 1, 2, 1), newpage = FALSE)

l <- timeVariation(KuwaitFilter2020, pollutant = "RawConc", main = "PM Concentrations (UG/M3) in 2020 with filter @200 pm ",  cols = "jet")
print(g, split = c(1, 1, 2, 1))
print(l, split = c(2, 1, 2, 1), subset = "month", newpage = FALSE)

```

```{r ##more polar plot}
polarPlot(KuwaitFilter2020, pollutant = "RawConc", main = " PM (UG/M3) from 2020 with filter at 200pm ",  cols = "jet", type = "month")

polarPlot(AVGKuwaitFilter2020, pollutant = "RawConc", main = "AVG PM (UG/M3) from 2020 with filter at 200pm ",  cols = "jet", type = "month")


polarPlot(AVGKuwaitFilter20172019, pollutant = "RawConc", main = "AVG PM (UG/M3) from 2017-2019 with filter at 200pm ",  cols = "jet", type = "month")

polarPlot(KuwaitFilter2019, pollutant = "RawConc", main = " PM (UG/M3) from 2017-2019 with filter at 200pm ",  cols = "jet", type = "month")

KuwaitFullJoinWS<- KuwaitFullJoin%>%
filter(ws <= 80)
polarPlot(KuwaitFullJoinWS, pollutant = "RawConc", main = " PM (UG/M3) from 2017-2020 ",  cols = "jet", type = "year")

AVGKuwaitFullJoinWS <- timeAverage(KuwaitFullJoinWS, avg.time = "day")
polarPlot(AVGKuwaitFullJoinWS, pollutant = "RawConc", main = "AVG PM (UG/M3) from 2017-2020 ",  cols = "jet", type = "year")

```


```{r}
polarCluster(AVGKuwaitFullJoinWS,pollutant = "RawConc", n.clusters=2:8  )


results8 <- polarCluster(KuwaitFullJoin, pollutant="RawConc", 
                        n.clusters = 8)
head(results8)
head(results8[["data"]])
results8 <- results8[["data"]]

table(results8[["cluster"]])


timeVariation(results8, pollutant = "RawConc", group = "cluster",
              key.columns = 4, cols = "jet",
             ci = FALSE, lwd = 3)

##From the clustering, we can see that cluster 7 has the most variation so lets pull that out and see what happens


##lets first try less clusters, I am currious

results4 <- polarCluster(OAFullJoin, pollutant="RawConc", 
                        n.clusters = 4)


head(results4)
head(results4[["data"]])
results4 <- results4[["data"]]

table(results4[["cluster"]])


timeVariation(results4, pollutant = "RawConc", group = "cluster",
              key.columns = 4, cols = "jet",
             ci = FALSE, lwd = 3)

##OKay lets pull out 3 from results 4 and 7 from results 8
timeVariation(filter(results4, cluster %in% c("1", "3")),
              pollutant = "RawConc",
              group = "cluster",  
               cols = "jet", lwd = 3)

timeVariation(filter(results8, cluster %in% c("3", "7")),
              pollutant = "RawConc",
              group = "cluster",  
     cols = "jet", lwd = 3)

##lets stick with 4 clusters and plot just a time series with the clusters
ggplot(data = results4, 
       mapping = aes(x = date,
                     y = RawConc,
                      fill = cluster,
                     color = cluster)) +  geom_line()+
  labs(title = "Clusters generated with open air plotted in a time series to observe the differences in pm", fill = "Year" )+ theme_bw()

##This plot was tooo busy so lets do avgs?

AvgOAFullJoin <- timeAverage(OAFullJoin, avg.time = "day")
AVGresults4 <- polarCluster(AvgOAFullJoin, pollutant="RawConc", 
                        n.clusters = 4)


head(AVGresults4)
head(AVGresults4[["data"]])
AVGresults4 <- AVGresults4[["data"]]

table(AVGresults4[["cluster"]])

ggplot(data = AVGresults4, 
       mapping = aes(x = date,
                     y = RawConc,
                      fill = cluster,
                     color = cluster)) +  geom_line()+
  labs(title = "AVG Clusters generated with open air plotted in a time series to observe the differences in pm", fill = "Year" )+ theme_bw()


##Just testing out some open air plots

timeProp(selectByDate(OAFullJoin ),
         pollutant = "RawConc", avg.time = "3 day",
         proportion = "wd", date.breaks = 10, key.position = "top",
         key.columns = 8, ylab = "PM 2.5 (UG/M3)")
##CPF analysis is very useful for showing which wind directions are dominated by high concentrations and give the probability of doing so.
timeProp(selectByDate(OAFullJoin, year = 2020),
         pollutant = "ws",
         avg.time = "3 day",
         n.levels = 5,
         cols = "viridis",
         proportion = "RawConc", date.breaks = 10,
         key.position = "top", key.columns = 3)

```


```{r}
OAFullJoin2 <- mutate(OAFullJoin, 
                 feature = ifelse(RawConc > 200 & visibility < 2, "Other", "Dust"))

timeVariation(OAFullJoin2, pollutant = "RawConc", 
              group = "feature", 
              difference = TRUE)


```


```{r for the paper}

##Playing around with these plots
calendarPlot(OAFullJoin, pollutant = "RawConc",year = 2017,
  breaks = c(0, 50, 100, 150, 1000),
  labels = c("Very low(0-49)", "Low(50-99)", "High(100-149)", "Very High(150-1000"),
  cols = "increment", statistic = "max")

calendarPlot(OAFullJoin, pollutant = "RawConc",year = 2018,
  breaks = c(0, 50, 100, 150, 1000),
  labels = c("Very low(0-49)", "Low(50-99)", "High(100-149)", "Very High(150-1000"),
  cols = "increment", statistic = "max")

##Used for paper
timePlot(selectByDate(OAFullJoin, year= 2020), pollutant = "RawConc", 
         avg.time = "day", xlab = "Month", ylab= "Raw Concentration (UG/M3)",main = "Time Series of Daily Averages for 2020")

timePlot(selectByDate(OAFullJoin),
         pollutant = c("RawConc"),
         y.relation = "free")

 polarCluster(AvgOAFullJoin, pollutant="RawConc", 
                        n.clusters = 4, main = "Polar Plot of Daily Average PM with Wind Speed and Direction Clustered")
 
 timePlot(OAFullJoin, 
         pollutant = c("RawConc", "visibility"),
         avg.time = "month", cols = "jet",
       y.relation = "free", main = "Time Series for Visibility and Raw Concentration with Monthly Averages")
 
 timeVariation(KuwaitFullJoin, pollutant = "RawConc", group = "Year", CI=  FALSE   )

 KuwaitFullJoin$Year <- as.factor(KuwaitFullJoin$Year)
 KuwaitFullJoin<- KuwaitFullJoin%>%
   filter(Year!= 2021)
timeVariation(KuwaitFullJoin, pollutant = "RawConc", group = "Year",
              key.columns = 4,
             ci = FALSE, main = "Diuranal Cylces for Unfiltered PM values from 2017-2020 ", ylab = "(UG/M3)", xlab = "Year" )


results4 <- polarCluster(AVGKuwaitBaseline, pollutant="RawConc", 
                        n.clusters = 4)


head(results4)
head(results4[["data"]])
results4 <- results4[["data"]]

table(results4[["cluster"]])

results5 <- polarCluster(KuwaitFullJoin, pollutant="RawConc", 
                        n.clusters = 5, main = "Polar Plot of Hourly PM (2017-2020) with Wind Speed and Direction Clustered")


results5 <- results5[["data"]]


results5 <- results5%>%
    filter(cluster!= 5)
timeVariation(results5, pollutant = "RawConc", group = "cluster",
              key.columns = 4,
             ci = FALSE, main = "Diuranal Cylces for Unfiltered PM values With Clusters 1-4", xlab= "Cluster", ylab = "(UG/M3)")


results6 <- results5%>%
    filter(cluster!= 4)

timeVariation(results6, pollutant = "RawConc", group = "cluster",
              key.columns = 3,
             ci = FALSE, main = "Diuranal Cylces for Unfiltered PM values With Clusters 1-3", xlab= "Cluster", ylab = "(UG/M3)")
polarPlot(results5,  pollutant = "RawConc",main = "Polar Plot with Clusters 1-4", xlab= "", ylab = "", type = "cluster", k = 1)
polarPlot(results6,  pollutant = "RawConc",main = "Polar Plot with Clusters 1-3 by Year", xlab= "", ylab = "", type = "year", k = 1)

 timePlot(results6, 
         pollutant = c("RawConc", "visibility"),
         avg.time = "month", cols = "jet",
       y.relation = "free", main = "Time Series for Visibility and Raw Concentration with Monthly Averages with Cluster 4 and 5 Filtered Out")
  timePlot(OAFullJoin, 
         pollutant = c("RawConc", "relh"),
          cols = "jet",
       y.relation = "free", main = "Time Series for Relative Humidity and Raw Concentration with Daily Averages", fontsize = 10)
   timePlot(selectByDate(results5, year = 2020),
         pollutant = c("RawConc")
    ,col= "jet",
     main = "Time Series for Raw Concentration with Raw Data from 2020", fontsize = 10, xlab= "Date")
   timePlot(selectByDate(results5, year = 2017:2019),
         pollutant = c("RawConc"),
         avg.time = "day" ,
     main = "Time Series for Raw Concentration with Daily Averages from 2017-2019", fontsize = 10, xlab= "Date")

```








